### ISSUE TITLE
검색창에서 아무것도 없을때 검색 버튼 누르면 이상한 페이지로 날라감, 레시피 검색 뒤로가기 버튼 안먹음

### ISSUE THREAD

**Issue by hazziu** [costcook-team/costcook-frontend#72]
검색창에서 아무것도 없을때 검색 버튼 누르면 이상한 페이지로 날라감

레시피 검색 뒤로가기 버튼 안먹음

![image](https://github.com/user-attachments/assets/79c524b7-961f-4688-9fd6-df666cb22185)

**Comment by devRonPark** [comment]
진행 중

**Comment by devRonPark** [comment]
해결 완료.
