### ISSUE TITLE
레시피 전체 목록에서 레시피 관련 글씨는 좌측정렬이 좋아보임 ( 중앙정렬하니깐 너무 뒤죽박죽임)

### ISSUE THREAD

**Issue by hazziu** [costcook-team/costcook-frontend#74]
레시피 전체 목록에서 레시피 관련 글씨는 좌측정렬이 좋아보임
( 중앙정렬하니깐 너무 뒤죽박죽임)

![image](https://github.com/user-attachments/assets/801e5b69-e36d-46e5-bcc7-dad5c7d8b19b)

**Comment by devRonPark** [comment]
진행 중

**Comment by devRonPark** [comment]
해결 완료.
